server:
    port: 9000

spring:
    application:
        name: zuul
eureka:
    client:
        service-url:
           # defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
           defaultZone: http://localhost:9003/eureka/, http://localhost:9004/eureka/,http://localhost:9005/eureka/ # 注册中心访问地址