server:
    port: 8086

spring:
    application:
        name: feign-api

eureka:
    instance:
        instance-id: feign-api-8086
        prefer-ip-address: true # 访问路径可以显示 IP
        lease-renewal-interval-in-seconds: 1
        lease-expiration-duration-in-seconds: 2
    client:
        service-url:
           # defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
           defaultZone:  http://localhost:9003/eureka/, http://localhost:9004/eureka/,http://localhost:9005/eureka/ # 注册中心访问地址